// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarWars.DataAccess.Data;

namespace StarWars.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200224064947_DataSeeding")]
    partial class DataSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StarWars.Core.Models.Appearance", b =>
                {
                    b.Property<int>("EpisodeId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.HasKey("EpisodeId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("Appearances");

                    b.HasData(
                        new
                        {
                            EpisodeId = 1,
                            CharacterId = 1
                        },
                        new
                        {
                            EpisodeId = 1,
                            CharacterId = 2
                        },
                        new
                        {
                            EpisodeId = 1,
                            CharacterId = 4
                        },
                        new
                        {
                            EpisodeId = 2,
                            CharacterId = 4
                        },
                        new
                        {
                            EpisodeId = 2,
                            CharacterId = 5
                        },
                        new
                        {
                            EpisodeId = 2,
                            CharacterId = 6
                        },
                        new
                        {
                            EpisodeId = 3,
                            CharacterId = 3
                        },
                        new
                        {
                            EpisodeId = 3,
                            CharacterId = 2
                        });
                });

            modelBuilder.Entity("StarWars.Core.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlanetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanetId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 63,
                            Description = "Smuggler",
                            Name = "Han Solo",
                            PlanetId = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 46,
                            Name = "Darth Vader"
                        },
                        new
                        {
                            Id = 3,
                            Age = 36,
                            Description = "Clone",
                            Name = "Boba Fett",
                            PlanetId = 3
                        },
                        new
                        {
                            Id = 4,
                            Age = 900,
                            Description = "Legendary Jedi Master",
                            Name = "Yoda"
                        },
                        new
                        {
                            Id = 5,
                            Age = 53,
                            Description = "One of the greatest Jedi Master",
                            Name = "Luke Skywalker",
                            PlanetId = 2
                        },
                        new
                        {
                            Id = 6,
                            Age = 54,
                            Name = "Princess Leia",
                            PlanetId = 4
                        });
                });

            modelBuilder.Entity("StarWars.Core.Models.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Episodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(1999, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Episode I – The Phantom Menace"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2002, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Episode II – Attack of the Clones"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2005, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Episode III – Revenge of the Sith"
                        });
                });

            modelBuilder.Entity("StarWars.Core.Models.Friendship", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("FriendId")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "FriendId");

                    b.HasIndex("FriendId");

                    b.ToTable("Friendships");

                    b.HasData(
                        new
                        {
                            CharacterId = 4,
                            FriendId = 1
                        },
                        new
                        {
                            CharacterId = 6,
                            FriendId = 1
                        },
                        new
                        {
                            CharacterId = 5,
                            FriendId = 1
                        },
                        new
                        {
                            CharacterId = 3,
                            FriendId = 2
                        },
                        new
                        {
                            CharacterId = 5,
                            FriendId = 4
                        },
                        new
                        {
                            CharacterId = 6,
                            FriendId = 5
                        },
                        new
                        {
                            CharacterId = 4,
                            FriendId = 6
                        });
                });

            modelBuilder.Entity("StarWars.Core.Models.Planet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Planets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Capital planet of the Corellian system",
                            Name = "Corellia"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Desert planet",
                            Name = "Tatooine"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Extragalactic planet",
                            Name = "Kamino"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Planetoid",
                            Name = "Polis Massa"
                        });
                });

            modelBuilder.Entity("StarWars.Core.Models.Appearance", b =>
                {
                    b.HasOne("StarWars.Core.Models.Character", "Character")
                        .WithMany("Appearances")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWars.Core.Models.Episode", "Episode")
                        .WithMany("Appearances")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StarWars.Core.Models.Character", b =>
                {
                    b.HasOne("StarWars.Core.Models.Planet", "Planet")
                        .WithMany()
                        .HasForeignKey("PlanetId");
                });

            modelBuilder.Entity("StarWars.Core.Models.Friendship", b =>
                {
                    b.HasOne("StarWars.Core.Models.Character", "Character")
                        .WithMany("CharacterFriends")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StarWars.Core.Models.Character", "Friend")
                        .WithMany("FriendCharacters")
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
